name: Rust

on:
  push:
    branches: ["main"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always    

    steps:
      - uses: actions/checkout@v4

      - name: Lint with rustfmt
        run: cargo fmt --all -- --check

      - name: Lint with clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      
      - name: Run tests
        run: cargo test --all-targets
